namespace Chaos.Extensions;

public class MapsToNotPunishDeathExtension
{
   public static readonly List<string> MapList =
    [
        "Mr. Hopps's Home",
        "Mythic",
        "Nightmare",
        "Cain's Farm",
        //Arena
        "Arena Underground",
        "Drowned Labyrinth Entrance",
        "Labyrinth Battle Ring",
        "Drowned Labyrinth - Pit",
        "Lava Arena",
        "Lava Arena - Teams",
        "Color Clash - Teams",
        "Hidden Havoc",
        "Escort - Teams",
        "Typing Arena",
        //End of Arena
        "Trial of Sacrifice",
        "Trial of Combat",
        "Trial of Luck",
        "Trial of Intelligence",
        "Mileth",
        "Abel",
        "Rucesion",
        "Undine",
        "Suomi",
        "Loures Castle",
        "Loures Castle Way",
        "Tagor",
        "Piet",
        "Rucesion Village Way",
        "Mileth Village Way",
        "Abel Port",
        "Suomi Village Way",
        "Undine Village Way",
        "Piet Village Way",
        "Nobis",
        "Macabre Yard",
        "Macabre Mansion",
        "Weapon Shop",
        "Armor Shop",
        "Rucesion Bank",
        "Mileth Storage",
        "Black Market",
        "Rucesion Jeweler",
        "Rucesion Church",
        "Rucesion Casino",
        "Rucesion Tailor",
        "Skills Master",
        "Rucesion Inn",
        "Shrine of Skandara",
        "Shrine of Miraelis",
        "Shrine of Theselene",
        "Shrine of Serendael",
        "Piet Empty Room",
        "Piet Inn",
        "Mileth Inn",
        "Abel Inn",
        "Suomi Inn",
        "Piet Storage",
        "Mileth Storage",
        "Piet Alchemy Lab",
        "Piet Tavern",
        "Mileth Tavern",
        "Undine Tavern",
        "Mileth Kitchen",
        "Piet Restaurant",
        "Piet Priestess",
        "Piet Magic Shop",
        "Piet Sewer Entrance",
        "Tagor Forge",
        "Tagor Inn",
        "Tagor Messenger",
        "Tagor Pet Store",
        "Tagor Storage",
        "Tagor Restaurant",
        "Tagor Tavern",
        "Tagor Church",
        "Abel Combat Skill Master",
        "Abel Fish Market",
        "Abel Tavern",
        "Abel Restaurant",
        "Abel Empty Room",
        "Abel Storage",
        "Abel Goods Shop",
        "Abel Magic Shop",
        "Abel Weapon Shop",
        "Abel Armor Shop",
        "Special Skills Masters",
        "Mileth Armor Shop",
        "Mileth Weapon Shop",
        "Special Spells Master",
        "Mileth Church",
        "Kitchen",
        "Restaurant",
        "Tavern",
        "Mileth Beauty Shop",
        "Temple of Choosing",
        "Undine Armor Shop",
        "Undine Weapon Shop",
        "Enchanted Haven",
        "Undine Goods Shop",
        "Undine Black Magic Master",
        "Undine Storage",
        "Undine Restaurant",
        "Undine Tavern",
        "Suomi Special Skill Master",
        "Garamonde Theatre",
        "Suomi Armor Shop",
        "Suomi Weapon Shop",
        "Suomi Cherry Farmer",
        "Suomi White Magic Master",
        "Suomi Combat Skill Master",
        "Suomi Black Magic Master",
        "Suomi Grape Farmer",
        "Suomi Restaurant",
        "Suomi Tavern",
        "Nobis Restaurant",
        "Nobis Tavern",
        "Nobis House",
        "Nobis Storage",
        "Nobis Weapon Shop",
        "Mileth Tailor",
        "Thanksgiving Challenge",
        "Santa's Challenge",
        "Training Grounds",
        "Damage Game"
    ];
}