name: Docs
on:
  push:
    branches:
      - release/v*

jobs:
  publish-docs:
    if: github.repository == 'Sichii/Chaos-Server'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - run: dotnet tool install -g docfx --version 2.74.1
      - run: docfx docs/docfx.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
          force_orphan: true
          cname: docs.chaos-server.net